// <auto-generated />
namespace ChatRoom_POC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _151017 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_151017));
        
        string IMigrationMetadata.Id
        {
            get { return "201710151139137_151017"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
